name = "Drydock Player"
author = "muggel_potato"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96ecbe5f5be75e6ad3c17db07a7b794a57e2f609e5776e1a832a496023530204"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.5"]
