name = "drydock"
author = "muggel_potato"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22dde6beb093f78a043aea04b43bedfbabd21966a94b549349feafb603ef67ac"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.5"]
