name = "Drydock Builder"
author = "muggel_potato"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9450b256087c77d6dea9ccc1d5f37ce313450545e085ff80d46bc4eebe8a9ab6"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.5"]
